In [1]:
import numpy as np
import pandas as pd

In [2]:
from scipy.stats import linregress

In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

In [4]:
from sklearn.svm import SVR
from sklearn.compose import TransformedTargetRegressor

In [34]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# create an imaginary dataset with 1000 observations
np.random.seed(0)
size = np.random.normal(2000, 500, 1000)
bedrooms = np.random.randint(1, 6, 1000)
age = np.random.normal(20, 5, 1000)
price = 50000 + 100 * size + 5000 * bedrooms - 1000 * age + np.random.normal(0, 10000, 1000)

# create a pandas data frame with the predictor and target variables
df = pd.DataFrame({'size': size, 'bedrooms': bedrooms, 'age': age, 'price': price})

In [59]:
# (size - 1000).astype(int) + [100, 100]

ValueError: operands could not be broadcast together with shapes (1000,) (2,) 

In [64]:
# Create two arrays with incompatible shapes
a = np.random.rand(1000)
b = np.array([2, 3])

In [65]:
a

array([1.12232362e-01, 7.94928903e-01, 2.07390986e-01, 6.95426581e-01,
       3.80853343e-01, 5.44759858e-01, 9.46206460e-01, 2.59179890e-01,
       3.01099457e-01, 2.92525417e-01, 3.70022727e-01, 5.76623437e-01,
       8.00251193e-01, 8.93113518e-01, 6.11888842e-02, 6.50096535e-01,
       5.92404596e-01, 6.00939059e-01, 7.93333312e-01, 9.37856265e-01,
       7.48256162e-01, 1.71624700e-01, 9.54651163e-01, 8.65206026e-01,
       2.99655426e-01, 1.22252334e-01, 8.05990602e-01, 9.76351825e-01,
       1.27487108e-01, 6.51359348e-01, 9.83688805e-03, 3.54929076e-02,
       7.85182210e-01, 8.15583583e-01, 3.49346163e-01, 4.47960371e-01,
       7.79477200e-01, 8.57704655e-01, 2.76100732e-01, 7.84287872e-01,
       2.00878052e-01, 4.47342247e-01, 7.18897252e-01, 6.85798425e-01,
       5.02289057e-01, 6.69873405e-01, 5.05328907e-02, 2.88267257e-01,
       2.16272968e-01, 8.17930757e-02, 2.07689135e-01, 8.60030138e-01,
       8.96279407e-01, 5.33106245e-01, 4.84395139e-01, 4.63167700e-01,
      

In [66]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.tile(A, (2, 3))

print(B)

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [5 6 5 6 5 6]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [5 6 5 6 5 6]]


In [68]:
A.ndim

2

In [67]:
B.ndim

2

In [69]:
# create an imaginary dataset with 1000 observations
np.random.seed(0)
size = np.random.normal(2000, 500, 1000)
bedrooms = np.random.randint(1, 6, 1000)
age = np.random.normal(20, 5, 1000)
price = 50000 + 100 * size + 5000 * bedrooms - 1000 * age + np.random.normal(0, 10000, 1000)

# create a pandas data frame with the predictor and target variables
df = pd.DataFrame({'size': size, 'bedrooms': bedrooms, 'age': age, 'price': price})

In [70]:
# fit a multiple linear regression model to the data
X = df[['size', 'bedrooms', 'age']]
y = df['price']
model = LinearRegression()
model.fit(X, y)

# print the coefficients of the model
print('Intercept:', model.intercept_)
print('Coefficients:', model.coef_)

# predict the price of a new house with size=2500, bedrooms=4, and age=15
new_house = [[2500, 4, 15]]
new_price = model.predict(new_house)
print('Predicted price:', new_price)

Intercept: 49973.80010935207
Coefficients: [  100.1066849   5002.31677251 -1021.96687993]
Predicted price: [304920.27624706]


C:\Users\k26ra\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
