In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
type (arr)

numpy.ndarray

In [5]:
arr = np.array(42)

print(arr)


42


In [6]:

arr.tostring()

C:\Users\k26ra\AppData\Local\Temp\ipykernel_4136\2934647770.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  arr.tostring()


b'*\x00\x00\x00'

In [7]:

arr.tobytes()

b'*\x00\x00\x00'

In [8]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [10]:

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])


2nd element on 1st row:  2


In [12]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr.shape

(2, 5)

In [14]:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10,11]])
# arr.shape

In [15]:
numpy_array = np.array([[1, 2], [1, 2]], dtype=int)
print(numpy_array)

[[1 2]
 [1 2]]


In [16]:
arr = np.array((1, 2, 3, 4))

In [17]:
arr

array([1, 2, 3, 4])

In [18]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [19]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [20]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [21]:
arr[1, 2]

8

### Slicing arrays

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1::2])

[2 4 6]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1::])

[2 3 4 5 6 7]


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::])

[1 2 3 4 5 6 7]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:])

[1 2 3 4 5 6 7]


In [28]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [29]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [30]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [31]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

int32
<U6


In [32]:
arr.ndim

1

In [33]:
arr.dtype

dtype('<U6')

In [34]:
type(arr.dtype)

numpy.dtype[str_]

In [35]:
arr = np.array([1, 2, 3, 4], dtype='S')
arr.dtype

dtype('S1')

In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='>S')

print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [38]:
# arr = np.array(['a', '2', '3'], dtype='i')